In [1]:
import pandas as pd

In [12]:
cities = ["New York", "Miami", "Chicago", "Seattle", "Austin"]
df = pd.DataFrame(cities, columns=["City"], 
                  index=["R1", "R2", "R3", "R4", "R5"])
df

        City
R1  New York
R2     Miami
R3   Chicago
R4   Seattle
R5    Austin

In [14]:
emp_data = [
    ["EMP_A", 28, "Engineering"],
    ["EMP_B", 24, "Marketing"],
    ["EMP_C", 32, "Engineering"],
    ["EMP_D", 29, "Sales"]
]
df = pd.DataFrame(emp_data, columns=["EMP_Name", "Age", "Department"],
                 index=["E01", "E02", "E03", "E04"])
df

    EMP_Name  Age   Department
E01    EMP_A   28  Engineering
E02    EMP_B   24    Marketing
E03    EMP_C   32  Engineering
E04    EMP_D   29        Sales

In [ ]:
print(df.shape)